# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build

on:
  push:
    tags:
    - '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode 14.2
      run: |
        sudo xcode-select -switch /Applications/Xcode_14.2.app
    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Dependencies
      run: |
        tuist fetch
    - name: Build
      run: |
        make build_release
    - uses: vimtor/action-zip@v1
      with:
        files: CompanionAI.app
        recursive: false
        dest: CompanionAI.app.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          CompanionAI.app.zip
