# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode 14.2
      run: |
        sudo xcode-select -switch /Applications/Xcode_14.2.app
    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Dependencies
      run: |
        tuist fetch
    - name: Build
      run: |
        tuist build --generate --configuration Release --build-output-path .build/
